### ISSUE TITLE
New template  [BUG]

### ISSUE THREAD

**Issue by dautovri** [dautovri/eve#9]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, MacOS]
 - Version [e.g. 6.6.3]
- Arch: [e.g.  arm64, amd64]

**Additional context**

**Comment by kgiori** [comment]
Some nit edits/suggestions follows, using this format:
current => my suggestion

To Reproduce => How to reproduce
Steps to reproduce the behavior: => Include a list of steps showing how to reproduce the bug.

Desktop (please complete the following information): => Environment

For the bullets, it's unclear to me what **Version** and **Arch** refer to -- are they to describe my computer or to define which EVE-OS I'm building/using? If EVE-OS, it could instead be something like this =>
* Your desktop/laptop OS and version [e.g., Linux, MacOS, MS Windows]
* EVE-OS version [e.g., 6.6.3]
* EVE-OS hardware architecture [e.g., arm64, amd64]

If instead it's only in regard to my computer, then =>
* OS [e.g., Linux, MacOS, MS Windows]
* OS Version [e.g., 6.6.3]
* OS Arch [e.g., arm64, amd64]

Add any other context about the problem here. => Add any other information about the problem here.
